// Batch status status enum.
export enum BATCH_STATUS {
  NOT_STARTED = 'NOT_STARTED',
  PROCESSING = 'PROCESSING',
  FINISHED_WITH_ERRORS = 'FINISHED_WITH_ERRORS',
  FINISHED_SUCCESSFULLY = 'FINISHED_SUCCESSFULLY'
}

export default BATCH_STATUS;
